core/urls.py
from django.urls import path

from core.views import (
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_complete_todo,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView, home_redirect,
)

urlpatterns = [
    path("", home_redirect, name="home"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/create", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"
    ),
    path(
        "tasks/<int:pk>/toggle-complete/",
        toggle_complete_todo,
        name="toggle-complete"
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "core"

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
]

core/models.py
from django.utils import timezone
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(blank=True, default=False)
    tags = models.ManyToManyField(to=Tag, related_name="tasks")

    def is_past_deadline(self):
        if self.deadline:
            now = timezone.now()
            return self.deadline < now

    class Meta:
        ordering = (
            "is_done",
            "-created_at",
        )

    def __str__(self):
        return self.content

core/forms.py
from django import forms

from core.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple()
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        required=False
    )

    class Meta:
        model = Task
        fields = [
            "content",
            "deadline",
            "tags",
        ]


class TaskSearchForm(forms.Form):
    content = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by content"}),
    )

core/views.py
from django.http import HttpRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from core.forms import TaskForm, TaskSearchForm
from core.models import Task, Tag


def home_redirect(request: HttpRequest) -> HttpResponseRedirect:
    return HttpResponseRedirect(reverse("core:task-list"))

class TaskListView(generic.ListView):
    model = Task

    def get_queryset(self):
        queryset = Task.objects.prefetch_related("tags")
        params = self.request.GET.get("content")

        if params:
            queryset = queryset.filter(content__icontains=params)

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        content = self.request.GET.get("content", "")
        context["form"] = TaskSearchForm(initial={"content": content})
        return context


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("core:task-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("core:task-list")


def toggle_complete_todo(
        request: HttpRequest,
        pk: int
) -> HttpResponseRedirect:
    task = get_object_or_404(Task, pk=pk)

    task.is_done = not task.is_done
    task.save()

    return HttpResponseRedirect(reverse("core:task-list"))


class TagListView(generic.ListView):
    model = Tag


class TagCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("core:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("core:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("core:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    {% block title %}<title>Todo List</title>{% endblock %}
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
  </head>
  
  <body>
  
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
            {% include "includes/sidebar.html" %}
          </div>
        <div class="col-sm-6">
            {% block content %}{% endblock %}
        </div>
      </div>
    </div>
  
  </body>

</html>

templates/core/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete <u>{{ tag }}</u>?</h1>
  <hr>
  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url "core:tag-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{% if object %}Update{% else %}Add new{% endif %} tag</h1>
  <br>
  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url "core:tag-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tags
    <a href="{% url "core:tag-create" %}" class="btn btn-primary" style="float: right">Add</a>
  </h1>
  <br>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Update</th>
      <th>Delete</th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td>{{ tag }}</td>
        <td><a href="{% url "core:tag-update" tag.id %}" class="btn btn-light">Update</a></td>
        <td><a href="{% url "core:tag-delete" tag.id %}" class="btn btn-danger">Delete</a></td>
      </tr>
    {% endfor %}
  </table>
{% endblock %}

templates/core/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Are you sure you want to delete <u>{{ task }}</u>?</h1>
  <hr>
  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Yes, delete" class="btn btn-danger">
    <a href="{% url "core:task-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{% if object %}Update{% else %}Create new{% endif %} TODO</h1>
  <form method="post" action="" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
    <a href="{% url "core:task-list" %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

templates/core/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    TODO List
    <a href="{% url "core:task-create" %}" class="btn btn-primary" style="float: right">Add task</a>
  </h1>
  <br>
  <form method="get" action="">
    {{ form|crispy }}
  </form>
  <div class="tasks-block">
    {% for task in task_list %}
      <div class="task">
        <h4>
          {{ task }}
          {% if task.is_done %}
            <span style="color: green">Done</span>
            <a href="{% url "core:toggle-complete" task.id %}" class="btn btn-secondary" style="float: right">Undo</a>
          {% else %}
            <span style="color: red">
              Not done
              {% if task.is_past_deadline %}
                | Past deadline!
              {% endif %}
            </span>
            <a href="{% url "core:toggle-complete" task.id %}" class="btn btn-success" style="float: right">Complete</a>
          {% endif %}
        </h4>
        <small>
          Created: {{ task.created_at }}
          {% if task.deadline %}
            <span style="color: #af0000; font-weight: bold">Deadline: {{ task.deadline }}</span>
          {% endif %}
        </small>
        <p class="text-muted">Tags:
        {% for tag in task.tags.all %}
          #{{ tag }}
        {% endfor %}
        <a href="{% url "core:task-update" task.id %}">Update</a>
        <a href="{% url "core:task-delete" task.id %}" style="color: red">Delete</a>
        </p>
        <hr>
      </div>
    {% endfor %}
  </div>
{% endblock %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item">
    <a href="{% url "core:task-list" %}">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url "core:tag-list" %}">Tags</a>
  </li>
</ul>